openapi: 3.0.0

info:
  title: IcM Comment Logic App Proxy
  description: Proxies a comment to the Discussion tab of an IcM incident via Logic App.
  version: "v1"

servers:
  - url: https://prod.microsofticm.com/api2/

paths:
  /incidentapi/incidents({Id}):
    patch:
      operationId: postIncidentComment
      summary: Post a comment to an IcM incident via Logic App
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                  description: The IcM incident ID
                Description:
                  type: string
                  description: The comment text to post
              required:
                - Id
                - Description
      responses:
        "200":
          description: Comment posted successfully
          content:
            application/json:
              schema:
                type: object
